version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-network
    # depends_on:
    #   database:
    #     condition: service_healthy
    command: bash -c "composer update && composer install && chmod -R 777 storage/ && php-fpm"
  server:
    image: nginx:latest
    # depends_on:
    #   database:
    #     condition: service_healthy
    ports:
      - '80:80'
    networks:
      - laravel-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p root" ]
      retries: 3
      timeout: 5s
    # volumes:
      # - "./database-local-scripts/tables.sql:/docker-entrypoint-initdb.d/1.sql"
networks:
  laravel-network:
    driver: bridge