version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-network
    command: bash -c "composer update && composer install && chmod -R 777 storage/ && php-fpm"
  server:
    image: nginx:latest
    ports:
      - '80:80'
    networks:
      - laravel-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  laravel-network:
    driver: bridge