version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - EVOLUTION_KEY=${EVOLUTION_KEY}
            - EVOLUTION_URL=${EVOLUTION_URL}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8080:8080

