version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - EVOLUTION_KEY=${EVOLUTION_KEY}
            - EVOLUTION_URL=${EVOLUTION_URL}
            - AWS_BUCKET=${AWS_BUCKET}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - JWT_SECRET=${JWT_SECRET}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8080:8080

