name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate
        run: make auth

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.digitalocean.com

      - name: Tag Docker image
        run: docker tag my-app registry.digitalocean.com/gesto-api/prod-gesto-items:latest

      - name: Push Docker image to registry
        run: docker push registry.digitalocean.com/gesto-api/prod-gesto-items:latest

      - name: SSH into Droplet and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.digitalocean.com/gesto-api/prod-gesto-items:latest
            docker stop gesto-items || true
            docker run -d --name gesto-items -p 80:8080 registry.digitalocean.com/gesto-api/prod-gesto-items:latest
